# Use new container infrastructure to enable caching
sudo: false

branches:
  only:
  - sources

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack.
matrix:
  include:
  - env: BUILD=stack
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
    compiler: ghc-8.0.2
    os: linux

install:
  - export PATH=$HOME/.local/bin::$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    case "$BUILD" in
      stack)
        if [ `uname` = "Darwin" ]
        then
          travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        else
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        fi
      ;;
    esac

script:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal build --install-ghc
      ;;
  esac
  ./script.hs build
  set +ex

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  fqdn: www.primetype.co.uk.
  email: nicolas@primetype.co.uk
  name: Nicolas Di Prima
  local_dir: ${TRAVIS_BUILD_DIR}/_site
  on:
    branch: sources
