# Use new container infrastructure to enable caching
sudo: false

branches:
  only:
  - sources

matrix:
  include:
  - language: generic
    os: linux

before_script:
  # Download and unzip the gutenberg executable
  # Replace the version numbers in the URL by the version you want to use
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

script:
  - zola build

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  fqdn: primetype.co.uk
  email: nicolas@primetype.co.uk
  name: Nicolas Di Prima
  local_dir: public
  on:
    branch: sources
